# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random Walk
#' 
#' Negative proportion of a Gaussian random walk.
#'
#' @param N Size of the walk.
#'
#' @examples
#' set.seet(1)
#' random_walk_neg_prop(1e6)
#'
#' @useDynLib advr38pkg
#' @export
#'
random_walk_neg_prop <- function(N) {
    .Call('_advr38pkg_random_walk_neg_prop', PACKAGE = 'advr38pkg', N)
}

